project/erp/urls.py
from . import views
from django.urls import path



app_name = 'erp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('show', views.show, name = 'show'),
    path('registerform', views.register_form, name = 'register_form'),
    path('registerdb', views.register_db, name = 'register_db'),
    path('registerjob', views.register_job, name = 'register_job'),
    path('registerjobdb', views.register_job_db, name = 'register_job_db')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('erp.urls'))
]

project/erp/models.py
from django.db import models
from django.utils import timezone

class Job(models.Model):
    name_job = models.CharField( max_length = 200 )
    description = models.CharField( max_length = 500 )

    def __str__(self):
        return self.name_job


class Employee(models.Model):
    name_employee = models.CharField( max_length = 200 )
    age = models.IntegerField( default = 0)
    email = models.EmailField( max_length = 200 )
    contract_date = models.DateField( default = timezone.now())
    job_status = models.ForeignKey( Job, on_delete = models.SET_NULL, null = True )

    def __str__(self):
        return self.name_employee

project/erp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Employee, Job



def index(request):
    job = Job.objects.count()
    employee = Employee.objects.count()
    return render(request, 'erp/index.html', {'job': job,
                                              'employee':employee})


def show(request):
    employees = Employee.objects.all()
    return render(request, 'erp/show.html', {'list_employees': employees,
                                             'null_message': employees.count() == 0})


def register_job(request):
    return render(request, 'erp/register_job.html',{})


def register_job_db(request):
    data = request.POST
    try:
        job = Job(name_job = data['name'], description = data['description'])
    except (KeyError):
        return render(request, 'erp/register_job.html', {'error_message':'Error en el formulario'})
    else:
        job.save()
        return HttpResponseRedirect(reverse('erp:index'))
    
    
def register_form(request):
    jobs = Job.objects.all
    return render(request, 'erp/register.html', {'jobs':jobs})


def register_db(request):
    try:
        data = request.POST
        job = Job.objects.get(pk = data['job'])
    except:
        return render(request, 'erp/register.html', {'error_message': 'Error en el formulario'})
    else:
        job.employee_set.create(name_employee = data['user'].title(), age = data['age'], email = data['email'])
        return HttpResponseRedirect(reverse('erp:index'))

project/erp/templates/erp/index.html
<h2>Menu de ERP</h2>

<menu>
    <button><a href="{% url 'erp:show' %}">Ver</a></button>
    <button><a href="{% url 'erp:register_form' %}">Registrar empleado</a></button>
    <button><a href="{% url 'erp:register_job' %}">Registrar puesto</a></button>
</menu>

<h3>Tabla de registros</h3>
<div>
    <p>{{employee}} empleado{{job | pluralize}}</p>
    <p>{{job}} puesto{{job | pluralize}}</p>
</div>

project/erp/templates/erp/register.html
<form action="{% url 'erp:register_db'  %}" method = "post">
{% csrf_token %}

    <fieldset>
        <legend><h2>Registro de empleado</h2></legend>

            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>    
            {% endif %}

            <label for="user">Nombre completo</label>
            <input type="text" name="user" required>

            <label for="number">Edad</label>
            <input type="number" name="age" required>

            <label for="email">Correo electronico</label>
            <input type="email" name="email" required>  


            <select name = "job">
                <option value="" disabled selected>Selecione puesto</option>
                {% for job in jobs %}
                    <option value="{{job.id}}">{{job.name_job}}</option>
                {% endfor %}
            </select>
            {% comment %} <label for="">Puesto</label> {% endcomment %}
            {% comment %} <input list = "jobs" name ="job" required autocomplete="off"> {% endcomment %}

    </fieldset>
    <button type="submit">Registrar empleado</button>
</form>
<button><a href="{% url 'erp:index' %}">Regresar a menu</a></button>

project/erp/templates/erp/register_job.html
<form action=" {% url 'erp:register_job_db' %}" method="post">
{% csrf_token %}

    <fieldset>
        <legend><h2>Registrar puesto laboral</h2></legend>
        {% if error_message %}
            <p><strong>Error de formulario</strong></p>
        {% endif %}

        <label for="name">Nombre</label>
        <input type="text" name="name" required>

        <label for="name">Descripcion</label>
        <input type="text" name="description" required>

    </fieldset>
    <button type="submit">Registrar puesto</button>
</form>
<button><a href="{% url 'erp:index' %}">Regresar a menu</a></button>

project/erp/templates/erp/show.html
<h2>Lista de empleados</h2>

{% if null_message %}
    <p><strong>No hay empleados registrados</strong></p>
{% endif %}

<main>
    <ul>
        <h3>ID</h3>
        {% for employee in list_employees %}
            <li>{{employee.id}}</li>
        {% endfor %}
    </ul>

    <ul>
        <h3>Nombre</h3>
        {% for employee in list_employees %}
            <li>{{employee.name_employee}}</li>
        {% endfor %}
    </ul>

    <ul>
        <h3>Edad</h3>
        {% for employee in list_employees %}
            <li>{{employee.age}}</li>
        {% endfor %}
    </ul>

    <ul>
        <h3>Correo</h3>
        {% for employee in list_employees %}
            <li>{{employee.email}}</li>
        {% endfor %}
    </ul>

    <ul>
        <h3>Puesto</h3>
        {% for employee in list_employees %}
            <li>{{employee.job_status}}</li>
        {% endfor %}
    </ul>


</main>

<button><a href="{% url 'erp:index' %}">Regresar a menu</a></button>